#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd
#script displays only username, userid and Home directory path for the user

while read passwd
do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
