#!/usr/bin/env bash
# Bash script that displays Best School 10 times using while loop
# then HI on the 9th iteration

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( i++ ))
done
