#!/usr/bin/env bash
# Bash script that displays Best School 10 times using while loop
# diaplays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "best School"
	fi
	(( i++ ))
done
